name: flutterapp
description: Base Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  intl: ^0.16.1
  flutter_bloc: ^6.1.0
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.3.3
  flutter_translator: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/locales/